---

- name: "loop test"
  hosts: all
  gather_facts: true
  #The module 'cisco.ios.ios_facts' that is called by 'gather_facts: true' no longer functions the same as in this video and will only return very basic top-level information about the host (hostname, image, iostype, version, model, serialnum, etc).
  #To gather the full amount of information available as seen in this video, it is required to add 'gather subset: all' directly under 'gather_facts: true'
  gather_subset: all 
  connection: network_cli

  tasks:
    - name: "loop through IP info"
      debug: 
        msg: "{{ ansible_facts.net_hostname }} has an IPv4 address of {{ item }}"
      loop: "{{ ansible_facts.net_all_ipv4_addresses }}"
      #alternative syntax: loop: "{{ ansible.net._all_ipv4_addresses }}" 
