---  #playbook to print variables associated with hosts

- name: PRINTING SOME VARIABLES
  hosts: all
  gather_facts: false

  tasks:
    - name: "displaying variables"
      debug:
        msg: "{{ hostvars[ansible_host].ospf.networks.0 }}"  #special Ansble keyword that prints variables for each host.  In this example the variable file 
        contains ospf variable info.  The 0 accesses the first network in the list under ospf networks variables.
