# How to programmatically access data that you have defined within your variable files



---  #playbook to print variables associated with hosts

- name: PRINTING SOME VARIABLES
  hosts: all
  gather_facts: false

  tasks:
    - name: "displaying variables"
      debug:
        msg: "{{ hostvars[ansible_host].ospf.networks.0 }}"  #special Ansble keyword that prints variables for each host.  In this example the variable file 
        contains ospf variable info.  The 0 accesses the first network in the list under ospf networks variables.
        
        
#anther example:

---

- name: PARSING SOME VARIABLES
  hosts: uk
  gather_facts: false

  tasks:
    - name: "parse variables"
      debug:
        msg: "The device is redistributing ASN: {{ hostvars[ansible_host].ospf.redistributing.bgp }}"  #


another example:

---

- name: "play to test some variable substitution"
  hosts: usa
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "task 1"
      cisco.ios.ios_config: 
        src: "eigrp/{{ eigrp_style }}.j2"  #this references an eigrp_style variable that is in the host variable files, directing it to templates of the same name

